### ISSUE TITLE
got error 'arr = [[self.vocab.stoi[x] for x in ex] for ex in arr] KeyError: 'in-house''

### ISSUE THREAD

**Issue by cjjjy** [tatsuokun/context2vec#4]
I run the code  ,it hints the error 'arr = [[self.vocab.stoi[x] for x in ex] for ex in arr] KeyError: 'in-house''

**Comment by tatsuokun** [comment]
We can replace the OOV words with unk symbol or write an exception for the case.
Related to this https://github.com/tatsuokun/context2vec/issues/3#issue-549406064

**Comment by cjjjy** [comment]
> We can replace the OOV words with unk symbol or write an exception for the case.
> Related to this [#3 (comment)](https://github.com/tatsuokun/context2vec/issues/3#issue-549406064)

thank you, it works
